context:
  version: "0.2.0"

package:
  name: analogjs-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@analogjs/language-server/-/language-server-${{ version }}.tgz
  sha256: 8de08e600c32f43af482178044943e3f572fd0d58812bc67e2ebe7dc25ad9abb

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "analog-language-server 2>&1 | grep -q \"Connection input stream is not set.\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: LSP server for AnalogJS Language Service
  homepage: https://analogjs.org/
  repository: https://github.com/analogjs/language-tools

extra:
  recipe-maintainers:
    - danielnachun
